POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "ford",
    "model": "mustang",
    "year": 1982,
    "mileage": 40000,
    "lng": 40,
    "lat": 40,
    "price": 10000
}


### Approve report
PATCH http://localhost:3000/reports/6
Content-Type: application/json

{
    "approved": false
}


### Get estimate
GET http://localhost:3000/reports?make=ford&model=mustang&year=1980&mileage=10000&lng=45&lat=45
