### List all messages
GET http://localhost:3000/messages


### Create new message
POST http://localhost:3000/messages
Content-Type: application/json

{
    "message": "hello"
}


### Get a particular message
GET http://localhost:3000/messages/123
