### Create User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "email22@domain.com",
    "password": "password2"
}

### Find User by id
GET http://localhost:3000/auth/1

### Find User by email
GET http://localhost:3000/auth?email=email22@domain.com

### Delete User
DELETE http://localhost:3000/auth/3

### Update user 
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "updated_email@email.com",
    "password": "werertrty"
}

